### ISSUE TITLE
`npm run bind-app secure-channels my-minimal-app` failing & docs update

### ISSUE THREAD

**Issue by mppub** [PrivateSky/ssapp-minimal-app#1]
Hello,
I have a few remarks while running this in my local dev env (macOs), all those things should be imo specified in the DOCS:

1. `npm run bind-app secure-channels my-minimal-app` fails if you do not run `npm run server` before.
2. clonning repo in the repo is something not-so-standard so I would specify it in the docs `explicitly` that you should clone this repo inside ssapp-demo-workspace
3. how can I deploy/run on localhost this app?

**Comment by alexgheorghiu** [comment]
@mmercdispose Please take the last version of the project and use the latest version of the README file and see if the problem still persist.
Also I added a section about how to use it.

**Comment by mppub** [comment]
Thanks @alexgheorghiu - works as expected
